### ISSUE TITLE
TofucraftReload

### ISSUE THREAD

**Issue by xfl03** [jihuayu/mod-build#25]
https://github.com/0999312/TofuCraftReload/archive/master.zip

**Comment by xfl03** [comment]
@jihuayu 麻烦看一下报错信息，好像编码有点问题，是否需要做一些特殊的设置呢？
本地编译试了下没有遇到编码问题

**Comment by jihuayu** [comment]
可能是因为windows是gbk编码的问题，我看下

**Comment by jihuayu** [comment]
我把默认编码改成了UTF-8，这回应该好了。 #26
